import 'package:doni_pizza/data/models/category_model.dart';
import 'package:doni_pizza/data/models/food_model.dart';
import 'package:doni_pizza/utils/helpers/uid.dart';
import 'package:doni_pizza/utils/helpers/uid.dart';
import 'package:doni_pizza/utils/helpers/uid.dart';
import 'package:doni_pizza/utils/helpers/uid.dart';
import 'package:doni_pizza/utils/helpers/uid.dart';
import 'package:doni_pizza/utils/helpers/uid.dart';
import 'package:doni_pizza/utils/helpers/uid.dart';

final List<CategoryModel> categories = [
  CategoryModel(
    id: UidGenerator.generateUID(),
    name: "Beverages",
    imageUrl: "images/category/beverages_image_url",
  ),
  CategoryModel(
    id: UidGenerator.generateUID(),
    name: "Soft Drinks",
    imageUrl: "images/category/soft_drinks_image_url",
  ),
  CategoryModel(
    id: UidGenerator.generateUID(),
    name: "Coffee and Tea",
    imageUrl: "images/category/coffee_and_tea_image_url",
  ),
  CategoryModel(
    id: UidGenerator.generateUID(),
    name: "Bakery",
    imageUrl: "images/category/bakery_image_url",
  ),
  CategoryModel(
    id: UidGenerator.generateUID(),
    name: "Fast Food",
    imageUrl: "images/category/fast_food_image_url",
  ),
  CategoryModel(
    id: UidGenerator.generateUID(),
    name: "Pizza",
    imageUrl: "images/category/pizza_image_url",
  ),
  CategoryModel(
    id: UidGenerator.generateUID(),
    name: "Extras",
    imageUrl: "images/category/extras_image_url",
  ),
];
final List<FoodItem> foodItems = [
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Moxito",
    description: "12 000",
    price: 12000.0,
    imageUrl: "images/foods/moxito_image_url",
    category: categories[0],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Flesh",
    description: "10 000",
    price: 10000.0,
    imageUrl: "images/foods/flesh_image_url",
    category: categories[0],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Gorilla",
    description: "10 000",
    price: 10000.0,
    imageUrl: "images/foods/gorilla_image_url",
    category: categories[0],
  ),
  FoodItem(
      id: UidGenerator.generateUID(),
      name: "Sok meva",
      description: "10 000",
      price: 10000.0,
      imageUrl: "images/foods/sok_meva_image_url",
      category: categories[0]),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Sok dena",
    description: "12 000",
    price: 12000.0,
    imageUrl: "images/foods/sok_dena_image_url",
    category: categories[0],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Dinay",
    description: "10 000",
    price: 10000.0,
    imageUrl: "images/foods/dinay_image_url",
    category: categories[0],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Gazsiz suv (1 l)",
    description: "3 000",
    price: 3000.0,
    imageUrl: "images/foods/gazsiz_suv_image_url",
    category: categories[0],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Gazsiz suv (0.5 l)",
    description: "2 000",
    price: 2000.0,
    imageUrl: "images/foods/gazsiz_suv_half_image_url",
    category: categories[0],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Cola baniwni",
    description: "7 000",
    price: 7000.0,
    imageUrl: "images/foods/cola_baniwni_image_url",
    category: categories[1],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Cola (0.5 l)",
    description: "6 000",
    price: 6000.0,
    imageUrl: "images/foods/cola_half_image_url",
    category: categories[1],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Cola (1 l)",
    description: "11 000",
    price: 11000.0,
    imageUrl: "images/foods/cola_one_liter_image_url",
    category: categories[1],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Cola (1.5 l)",
    description: "15 000",
    price: 15000.0,
    imageUrl: "images/foods/cola_one_point_five_liter_image_url",
    category: categories[1],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Fanta baniwni",
    description: "7 000",
    price: 7000.0,
    imageUrl: "images/foods/fanta_baniwni_image_url",
    category: categories[1],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Fanta (0.5 l)",
    description: "6 000",
    price: 6000.0,
    imageUrl: "images/foods/fanta_half_image_url",
    category: categories[1],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Fanta (1 l)",
    description: "11 000",
    price: 11000.0,
    imageUrl: "images/foods/fanta_one_liter_image_url",
    category: categories[1],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Fanta (1.5 l)",
    description: "15 000",
    price: 15000.0,
    imageUrl: "images/foods/fanta_one_point_five_liter_image_url",
    category: categories[1],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Coffee (3 in 1)",
    description: "3 000",
    price: 3000.0,
    imageUrl: "images/foods/coffee_three_in_one_image_url",
    category: categories[2],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Cappuccino",
    description: "6 000",
    price: 6000.0,
    imageUrl: "images/foods/cappuccino_image_url",
    category: categories[2],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Choy",
    description: "3 000",
    price: 3000.0,
    imageUrl: "images/foods/choy_image_url",
    category: categories[2],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Lavash oddiy",
    description: "20 000",
    price: 20000.0,
    imageUrl: "images/foods/lavash_odd_image_url",
    category: categories[3],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Lavash sirli",
    description: "23 000",
    price: 23000.0,
    imageUrl: "images/foods/lavash_sirli_image_url",
    category: categories[3],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Tandir lavash oddiy",
    description: "25 000",
    price: 25000.0,
    imageUrl: "images/foods/tandir_lavash_odd_image_url",
    category: categories[3],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Tandir lavash sirli",
    description: "27 000",
    price: 27000.0,
    imageUrl: "images/foods/tandir_lavash_sirli_image_url",
    category: categories[3],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Hot dog kanadskiy",
    description: "10 000",
    price: 10000.0,
    imageUrl: "images/foods/hot_dog_kanadskiy_image_url",
    category: categories[4],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Hot dog kanadskiy (2x)",
    description: "13 000",
    price: 13000.0,
    imageUrl: "images/foods/hot_dog_kanadskiy_2x_image_url",
    category: categories[4],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Xaggi",
    description: "15 000",
    price: 15000.0,
    imageUrl: "images/foods/xaggi_image_url",
    category: categories[4],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Xaggi sirli",
    description: "20 000",
    price: 20000.0,
    imageUrl: "images/foods/xaggi_sirli_image_url",
    category: categories[4],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Hot dog qazili",
    description: "25 000",
    price: 25000.0,
    imageUrl: "images/foods/hot_dog_qazili_image_url",
    category: categories[4],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Donar",
    description: "18 000",
    price: 18000.0,
    imageUrl: "images/foods/donar_image_url",
    category: categories[4],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Donar sirli",
    description: "20 000",
    price: 20000.0,
    imageUrl: "images/foods/donar_sirli_image_url",
    category: categories[4],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Big donar",
    description: "30 000",
    price: 30000.0,
    imageUrl: "images/foods/big_donar_image_url",
    category: categories[4],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Big donar sirli",
    description: "40 000",
    price: 40000.0,
    imageUrl: "images/foods/big_donar_sirli_image_url",
    category: categories[4],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Gamburger",
    description: "15 000",
    price: 15000.0,
    imageUrl: "images/foods/gamburger_image_url",
    category: categories[4],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Chizburger",
    description: "20 000",
    price: 20000.0,
    imageUrl: "images/foods/chizburger_image_url",
    category: categories[4],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Big burger",
    description: "25 000",
    price: 25000.0,
    imageUrl: "images/foods/big_burger_image_url",
    category: categories[4],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Big chizburger",
    description: "28 000",
    price: 28000.0,
    imageUrl: "images/foods/big_chizburger_image_url",
    category: categories[4],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Hot dog karalevskiy",
    description: "20 000",
    price: 20000.0,
    imageUrl: "images/foods/hot_dog_karalevskiy_image_url",
    category: categories[4],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Pide",
    description: "35 000",
    price: 35000.0,
    imageUrl: "images/foods/pide_image_url",
    category: categories[4],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Pitsa assarti (69k/79k)",
    description: "69,000/79,000",
    price: 69000.0,
    imageUrl: "images/foods/pitsa_assarti_image_url",
    category: categories[5],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Pitsa tovuqli (69k/79k)",
    description: "69,000/79,000",
    price: 69000.0,
    imageUrl: "images/foods/pitsa_tovuqli_image_url",
    category: categories[5],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Pitsa peperoni (69k/79k)",
    description: "69,000/79,000",
    price: 69000.0,
    imageUrl: "images/foods/pitsa_peperoni_image_url",
    category: categories[5],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Pitsa goshtli (69k/79k)",
    description: "69,000/79,000",
    price: 69000.0,
    imageUrl: "images/foods/pitsa_goshtli_image_url",
    category: categories[5],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Pitsa qazili (90k/100k)",
    description: "90,000/100,000",
    price: 90000.0,
    imageUrl: "images/foods/pitsa_qazili_image_url",
    category: categories[5],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Pitsa margarita (59k/69k)",
    description: "59,000/69,000",
    price: 59000.0,
    imageUrl: "images/foods/pitsa_margarita_image_url",
    category: categories[5],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Non",
    description: "3 000",
    price: 3000.0,
    imageUrl: "images/foods/non_image_url",
    category: categories[6],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Sous mayonez",
    description: "3 000",
    price: 3000.0,
    imageUrl: "images/foods/sous_mayonez_image_url",
    category: categories[6],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Sous ketchup",
    description: "3 000",
    price: 3000.0,
    imageUrl: "images/foods/sous_ketchup_image_url",
    category: categories[6],
  ),
  FoodItem(
    id: UidGenerator.generateUID(),
    name: "Sous sirli",
    description: "3 000",
    price: 3000.0,
    imageUrl: "images/foods/sous_sirli_image_url",
    category: categories[6],
  ),
];
